### ISSUE TITLE
Delta 7B Problems When Pasting Lists

### ISSUE THREAD

**Issue by JediOswald** [FreakyDug/r2-d7#67] opened 2022-03-29 17:42 UTC
When Pasting a YASB link into discord with the Delta 7B variations of Ashoka, Jedi Knight, and Obi-Wan, it gives you an unknown pilot error.
When Pasting an LBN link into discord with ANY Delta 7B pilot, it just says it is the normal Delta 7 variation.

It is a different problem for both YASB and LBN and would need a solution for each.

Screenshots from Discord:

![YASB](https://user-images.githubusercontent.com/87926233/160672654-a66e0470-d55e-4fd9-bcf6-ad66a75e4dc8.PNG)
![LBN](https://user-images.githubusercontent.com/87926233/160672702-59c120eb-cda9-4a8c-9f83-33af9535d869.PNG)

**Comment by danrs** [comment] 2022-03-30 02:10
YASB: Looks like YASB is correct, so the issue probably lies in squad2xws. The squad2xws dev has been notified.

LBN: The error is caused by LBN using incorrect XWS ID for 7B pilots. The the dev has been notified.

**Comment by danrs** [comment] 2022-03-30 02:52
YASB fix is in this PR: https://github.com/zacharyp/squad2xws/pull/8
LBN fix has been requested in this issue: https://github.com/andrelind/launch-bay-next-web/issues/98

I am now closing this issue as no code changes are needed in R2D7

**Closed by danrs** 2022-03-30 02:52 UTC
